name: Merge to Main

on:
  workflow_run:
    workflows: ["Node.js Unit Testing"]
    types:
      - completed

jobs:
  merge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge to main
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git merge --no-ff ${{ github.event.workflow_run.head_branch }} -m "Merge ${{ github.event.workflow_run.head_branch }} to main"
